baseURL = "https://relationalagents.com/"
languageCode = "en-us"
title = "Relational Agents Group"
theme = "rag-theme"

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    description = "Relational Agents Group website"

[[menu.main]]
    url = "/project"
    name = "projects"
    weight = 2
[[menu.main]]
    url = "/people"
    name = "people"
    weight = 1
[[menu.main]]
    url = "/publication"
    name = "publications"
    weight = 3
[[menu.main]]
    url = "/demo"
    name = "demoes"
    weight = 4
[[menu.main]]
    url = "/press"
    name = "press"
    weight = 5

[[ menu.main ]]
    url = "/project/archive"
    name = "past"
    parent = "projects"
[[ menu.main ]]
    url = "/project"
    name = "current"
    parent = "projects"

[taxonomies]
tag = "tags"
category = "categories"
year = "years"